# Generated by Django 3.2.5 on 2021-07-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='tour',
            field=models.ManyToManyField(related_name='seat', to='qldlapp.Tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='stock',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
