# Generated by Django 3.2.5 on 2021-07-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldlapp', '0003_auto_20210728_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
