# Generated by Django 3.2.5 on 2021-07-29 01:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qldlapp', '0004_alter_seat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
