# Generated by Django 3.2.5 on 2021-07-29 04:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qldlapp', '0006_alter_tour_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
    ]
