# Generated by Django 3.2.5 on 2021-07-29 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldlapp', '0007_alter_tour_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='seat',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='seat',
            field=models.ManyToManyField(related_name='khachhang', to='qldlapp.Seat'),
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='tour',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='tour',
            field=models.ManyToManyField(related_name='khachhang', to='qldlapp.Tour'),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='tour',
        ),
        migrations.AddField(
            model_name='seat',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='qldlapp.tour'),
        ),
    ]
