# Generated by Django 3.2.5 on 2021-07-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldlapp', '0008_auto_20210729_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_day', models.DateTimeField(auto_now_add=True)),
                ('upload_day', models.DateTimeField(auto_now=True)),
                ('tour', models.ManyToManyField(related_name='tag', to='qldlapp.Tour')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to='avatar/%Y/%m'),
        ),
        migrations.DeleteModel(
            name='Khachhang',
        ),
    ]
