# Generated by Django 3.2.5 on 2021-07-30 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldlapp', '0009_auto_20210730_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='qldlapp.tour'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tour',
            field=models.ManyToManyField(related_name='tags', to='qldlapp.Tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='qldlapp.city'),
        ),
    ]
