# Generated by Django 3.2.5 on 2021-08-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldlapp', '0010_auto_20210730_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tour',
            field=models.ManyToManyField(blank=True, related_name='tags', to='qldlapp.Tour'),
        ),
    ]
