# Generated by Django 3.2.5 on 2021-10-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldlapp', '0014_auto_20211001_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
